# Generated by Django 3.0.1 on 2019-12-26 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=120)),
                ('pro_content', models.TextField(default='글을 쓰지 않았어요')),
                ('pro_date', models.DateTimeField(auto_now=True)),
                ('pro_link', models.CharField(max_length=250, null=True)),
                ('pro_sub', models.IntegerField(default=0, null=True)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
