# Generated by Django 3.0.1 on 2019-12-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=120)),
                ('pro_content', models.TextField(default='글을 쓰지 않았어요')),
                ('pro_date', models.DateTimeField(auto_now=True)),
                ('pro_link', models.CharField(max_length=250, null=True)),
                ('pro_sub', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
