# Generated by Django 3.0.1 on 2019-12-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_project_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
