# Generated by Django 3.0.1 on 2019-12-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20191227_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_name',
            new_name='user',
        ),
    ]
