# Generated by Django 3.0.1 on 2019-12-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20191227_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='user_id',
        ),
    ]
