# Generated by Django 3.0.1 on 2019-12-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_title', models.CharField(max_length=120)),
                ('port_content', models.TextField(default='글을 쓰지 않았어요')),
                ('port_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
