# Generated by Django 3.0.1 on 2019-12-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='port_file',
        ),
    ]
