# Generated by Django 2.2.7 on 2019-12-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brd_title', models.CharField(max_length=120)),
                ('brd_content', models.TextField(default='글을 쓰지 않았어요')),
                ('brd_date', models.DateTimeField(auto_now=True)),
                ('brd_count', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
